spring.application.name=my blog

spring.datasource.url=jdbc:mysql://localhost:3306/db_myblog?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=biBip

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Le secret doit contenir au moins 32 caractères
security.jwt.secret-key=eyJhbGciOiJIUzI1NiJ9eyJSb2xlI7joiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc0MTYyNTM3NywiaWF0IjoxNzQxNjI1Mzc3fQ8FwLt8Xd4dQmr6NPve1YsSZ2sIfs16avLdhZ6DD1YE8U

# 1h in millisecond
security.jwt.expiration-time=3600000